### ISSUE TITLE
tweaks for core

### ISSUE THREAD

**Issue by sorahn** [sorahn/factorio_noir#6]
* update yaml to allow base and core to be referenced from the same file.
* the 'includes' list needs to be able to be files too, not just directories
* add dev flag to ENV
* print early if dev mode
* remove version number from /dist/factorio-noir folder (and don't delete it, just empty it) so we can use the symlinks to factorio for dev

**Comment by sorahn** [comment]
example for the new 'overlays.yaml' file I want to include:

```
core:
  graphics:
    - artillery-impact-map-visualization
    - visualization-construction-radius
    - visualization-logistic-radius
    - pollution-visualization

base:
  graphics:
    entity:
      small-electric-pole:
        - electric-pole-radius-visualization
```

**Comment by Larandar** [comment]
Easy part:
- [x] Remove version number from /dist/factorio-noir, and don't remove it
- [x] Print dev status early
- [x] Add envvar for DEV

Less easy:
- [x] Allow categories to be cross mods (Or generate multiple from one yml file?)
- [x] Fix that file at the root of `graphics` directory can not be modified

**Comment by Larandar** [comment]
To clarify, all YAML files would not have a `mod` property, instead each key that is not `treatment` is evaluated as mod?

**Comment by sorahn** [comment]
> To clarify, all YAML files would not have a mod property, instead each key that is not treatment is evaluated as mod?


Good point, how about:

```
treatment:
  brigntness: 0.5
  saturation: 0.7

sprites:
  core:
    graphics:
      - artillery-impact-map-visualization
      - visualization-construction-radius
      - visualization-logistic-radius
      - pollution-visualization

  base:
    graphics:
      entity:
        small-electric-pole:
          - electric-pole-radius-visualization
```
